apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-v2
  labels:
    app: springboot-app-v2
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: java-service
    tags.datadoghq.com/version: "0.0.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-v2
      tags.datadoghq.com/service: java-service
      tags.datadoghq.com/env: dev
      tags.datadoghq.com/version: "0.0.2"
  template:
    metadata:
      labels:
        app: springboot-app-v2
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: java-service
        tags.datadoghq.com/version: "0.0.2"
        admission.datadoghq.com/enabled: "true"
      annotations:
        # Auto-inject the Datadog Java tracer
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/java-lib.version: "v1.50.0"
        # Point tracer at node's Agent
        admission.datadoghq.com/config.mode: "hostip"
        # Collect stdout/stderr as logs for THIS container
        ad.datadoghq.com/java-service.logs: >-
          [{"source":"java","service":"java-service","auto_multi_line_detection": true}]
    spec:
      containers:
        - name: springboot-app-v2
          image: sumanth17121988/springbootmetric:2
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics-port
              containerPort: 8881
          env:
            # JVM Heap settings
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx700m"

            # Unified service tags
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']

            # Tracing, profiling, DI, JMX, AppSec
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_TRACE_HEALTH_METRICS_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
              value: "true"
            - name: DD_JMXFETCH_ENABLED
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
            - name: DD_APPSEC_SCA_ENABLED
              value: "true"
            - name: DD_PROFILING_DDPROF_LIVEHEAP_ENABLED
              value: "true"
            - name: DD_PROFILING_HEAP_ENABLED
              value: "true"
            - name: DD_PROFILING_DIRECTALLOCATION_ENABLED
              value: "true"
            # Optional: global tags (maps to dd.tags)
            - name: DD_TAGS
              value: "app-name:java-service,team:devops"
            # Tracer -> node Agent (DaemonSet) on 8126
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_URL
              value: "http://$(DD_AGENT_HOST):8126"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service-v2
  labels:
    app: springboot-app-v2
spec:
  type: ClusterIP
  selector:
    app: springboot-app-v2
    tags.datadoghq.com/service: java-service
  ports:
    - name: metrics-port
      protocol: TCP
      port: 80
      targetPort: 8881

